#ifndef GUARD_GAUNTLET_H
#define GUARD_GAUNTLET_H

void GauntletStart(struct ScriptContext *ctx);
void GauntletEnd(struct ScriptContext *ctx);
void CallnativeGauntletItemBall(struct ScriptContext *ctx);
//static void InitGauntletBagItems(void);
//static void RespawnAbout24RandomGauntletItemBalls(void);
//static bool32 GauntletPartySetup(void);
//static bool32 SquashEarthRibbonInfo(void);
u32 GauntletReadRng(u32 integer);
void TryUpdateRocksReveal(void);
enum Item GauntletReturnRngMint(void);

void ScrCmd_LoadGauntletBoonInVarResultToboosboog(struct ScriptContext *ctx);
void AddDevotionTo0x8008(void);
void ScrCmd_DoGauntletBoonList(struct ScriptContext *ctx);
void UpdateDevotions(void);

enum ItemPool {
    GAUNTLET_ITEM_POOL_LOW,
    GAUNTLET_ITEM_POOL_MED,
    GAUNTLET_ITEM_POOL_HIGH,
    GAUNTLET_ITEM_POOL_END
};

enum GauntletAltar{
    GAUNTLET_ALTAR_HP_1 = 0,//eldwurm 
    GAUNTLET_ALTAR_ATK_2 = 3,//titan, groudon OR REGI
    GAUNTLET_ALTAR_DEF_3 = 6,//nereid, kyogre
    GAUNTLET_ALTAR_SPEED_4 = 9,//winged lion, arceus fight
    GAUNTLET_ALTAR_SPATK_5 = 12,//Dark Void, guzzlord
    GAUNTLET_ALTAR_SPDEF_6 = 15,//SAPROTROPH, harvest, shaymin sky
    GAUNTLET_ALTAR_BOSS_7 = 18,// scary legendaries
    GAUNTLET_ALTAR_MAX = 24
};// unused.

enum GauntletTypes
{
    TYPE_SAPROTROPH = 0,// grass bug poison. "Harvest" Shaymin Sky. 
    TYPE_NEREID = 1, // water ice fairy "Depths" kyogre alpha
    TYPE_ELDWYRM = 2, // fire electric dragon. "Elder Dragon" Fused kyurem.
    TYPE_DSOTM = 3, // ghost dark psy normal. "Void" Guzzlord.
    TYPE_MONOLITH =4, //rock steel ground. "Mountains". Regigigas? Groudon omega?
    TYPE_WINGED_LION = 5, // fight fly. "Heavens" Arceus-Fighting?
    TYPE_COLOURLESS = 6,
    TYPE_DEVOTION_LENGTH = TYPE_COLOURLESS,
    TYPE_GAUNTLET_LENGTH,
};

enum GauntletRarity
{
    RARITY_STAPLE = 0,
    RARITY_COMMON = 1,
    RARITY_RARE = 2,
    RARITY_EPIC = 3,
    RARITY_LENGTH,
};

enum BoonType
{
    BOON_ITEM = 0,
    BOON_TM = 1,
    BOON_HM =2,
    BOON_FLAG=3,
    BOON_TUTOR=4,
    BOON_30_BERRIES=5,
    BOON_TERRAIN_SEEDS=6,
    BOON_MONEY=7,
    BOON_XDEFXSPDEF=8,
    BOON_3RANDOMTMS=9,
    BOON_10XITEM=10,
    BOON_10IRON10HPUP10ZINC=11,
    BOON_REROLL=12,
    BOON_REROLLPLUSTUTOR=13,
    BOON_TOXICANDFLAMEORB=14,
    BOON_TYPE_LENGTH=15,
    BOON_XATTACKXSPECIAL=16,
};

enum GauntletBoon {
    GB_TOXIC = 0,     SAPROTROPH_STAPLE = GB_TOXIC,
    GB_30_RANDOM_BERRIES = 1,
    GB_LIFE_DEW = 2,     NEREID_STAPLE = GB_LIFE_DEW,
    GB_EXP_SHARE = 3,
    GB_CHOICE_SCARF = 4,     ELDWYRM_STAPLE = GB_CHOICE_SCARF,
    GB_LIFE_ORB = 5,
    GB_PROTECT = 6,     DSOTM_STAPLE = GB_PROTECT,
    GB_EVIOLITE = 7,     MONOLITH_STAPLE = GB_EVIOLITE,
    GB_10X_HYPER_POTION = 8,
    GB_SHOCK_SHIELD = 9,
    GB_FOCUS_SASH = 10,     WINGED_LION_STAPLE = GB_FOCUS_SASH,
    GB_REROLL_INTO_WINGED_LION = 11,
    GB_AROMATHERAPY = 12,     SAPROTROPH_COMMON = GB_AROMATHERAPY,
    GB_LEECH_SEED = 13,
    GB_WORRY_SEED = 14,
    GB_TWINEEDLE = 15,
    GB_U_TURN = 16,
    GB_VENOM_DRENCH = 17,
    GB_VENOSHOCK = 18,
    GB_BLACK_SLUDGE = 19,
    GB_SHED_SHELL = 20,
    GB_20_TERRAIN_SEEDS = 21,
    GB_BIG_ROOT = 22,
    GB_TOXIC_ORB_AND_FLAME_ORB = 23,
    GB_MIRACLE_SEED = 24,
    GB_SILVER_POWDER = 25,
    GB_POISON_BARB = 26,
    GB_STICKY_BARB = 27,
    GB_CUT = 28,
    GB_SAFETY_GOGGLES = 29,
    GB_AQUA_RING = 30,     NEREID_COMMON = GB_AQUA_RING,
    GB_RAIN_DANCE = 31,
    GB_SOAK = 32,
    GB_AURORA_VEIL = 33,
    GB_HAIL = 34,
    GB_DRAINING_KISS = 35,
    GB_MONEY = 36,
    GB_SNOW = 37,
    GB_MISTY = 38,
    GB_ICE_PUNCH = 39,
    GB_FLAME_CHARGE = 40,     ELDWYRM_COMMON = GB_FLAME_CHARGE,
    GB_SUNNY_DAY = 41,
    GB_FIRE_PUNCH = 42,
    GB_THUNDER_PUNCH = 43,
    GB_EXPLOSION = 44,
    GB_DRAGON_CHEER = 45,
    GB_EXPERT_BELT = 46,
    GB_CHARCOAL = 47,
    GB_MAGNET = 48,
    GB_DRAGON_FANG = 49,
    GB_DRAGON_BREATH = 50,
    GB_BATON_PASS = 51,     DSOTM_COMMON = GB_BATON_PASS,
    GB_ENCORE = 52,
    GB_ENDEAVOR = 53,
    GB_HIDDEN_POWER = 54,
    GB_PAIN_SPLIT = 55,
    GB_SLEEP_TALK = 56,
    GB_SUBSTITUTE = 57,
    GB_WEATHER_BALL = 58,
    GB_WISH = 59,
    GB_CALM_MIND = 60,
    GB_LIGHT_SCREEN = 61,
    GB_PSYCHO_CUT = 62,
    GB_REFLECT = 63,
    GB_TRICK = 64,
    GB_TRICK_ROOM = 65,
    GB_CURSE = 66,
    GB_DESTINY_BOND = 67,
    GB_HONE_CLAWS = 68,
    GB_TAUNT = 69,
    GB_SOFT_BOILED = 70,
    GB_COPYCAT = 71,
    GB_LASER_FOCUS = 72,
    GB_POWER_SPLIT = 73,
    GB_BODY_SLAM = 74,
    GB_COUNTER = 75,
    GB_DEFENSE_CURL = 76,
    GB_DREAM_EATER = 77,
    GB_WIZARD_CAPE = 78,
    GB_ROCK_SMASH = 79,     MONOLITH_COMMON = GB_ROCK_SMASH,
    GB_STRENGTH = 80,
    GB_AUTOTOMIZE = 81,
    GB_STEEL_BEAM = 82,
    GB_IRON_DEFENSE = 83,
    GB_ANCIENT_POWER = 84,
    GB_SANDSTORM = 85,
    GB_DIG = 86,
    GB_SAND_TOMB = 87,
    GB_ROCK_SLIDE_TUTOR = 88,
    GB_ROLLOUT = 89,
    GB_MUD_SLAP = 90,
    GB_ROCKY_HELMET = 91,
    GB_ASSAULT_VEST = 92,
    GB_HEAVY_DUTY_BOOTS = 93,
    GB_10X_X_DEFEND,_10X_X_SP_DEF = 94,
    GB_10X_FULL_RESTORE = 95,
    GB_COVERT_CLOAK = 96,
    GB_10X_PP_UP = 97,
    GB_BULK_UP = 98,     WINGED_LION_COMMON = GB_BULK_UP,
    GB_COACHING = 99,
    GB_POWER_UP_PUNCH = 100,
    GB_UPPER_HAND = 101,
    GB_ROOST = 102,
    GB_TAILWIND = 103,
    GB_WHIRLWIND = 104,
    GB_SEISMIC_TOSS = 105,
    GB_FOCUS_BAND = 106,
    GB_SHARP_BEAK = 107,
    GB_PUNCHING_GLOVE = 108,
    GB_EJECT_PACK = 109,
    GB_EJECT_BUTTON = 110,
    GB_RED_CARD = 111,
    GB_AIR_BALLOON = 112,
    GB_FLYING_GEM = 113,
    GB_TUTOR_METRONOME_AND_REROLL = 114,
    GB_FLAIL = 115,
    GB_ENDURE = 116,
    GB_10X_X_SPEED = 117,
    GB_FALSE_SWIPE = 118,     UNIVERSAL_COMMON = GB_FALSE_SWIPE,
    GB_MEGA_KICK = 119,
    GB_MEGA_PUNCH = 120,
    GB_SWAGGER = 121,
    GB_SWIFT = 122,
    GB_PSYCH_UP = 123,
    GB_SNORE = 124,
    GB_INVERSE_BATTLE = 125,
    GB_WONDER_ROOM = 126,
    GB_FLASH = 127,
    GB_GIGA_DRAIN = 128,     SAPROTROPH_RARE = GB_GIGA_DRAIN,
    GB_SOLAR_BEAM = 129,
    GB_STICKY_WEB = 130,
    GB_X_SCISSOR = 131,
    GB_NATURE_POWER = 132,
    GB_GRASSY_TERRAIN = 133,
    GB_WATERFALL = 134,     NEREID_RARE = GB_WATERFALL,
    GB_DIVE = 135,
    GB_BLIZZARD = 136,
    GB_TRIPLE_AXEL = 137,
    GB_DAZZLING_GLEAM = 138,
    GB_RAINY_WEATHER = 139,
    GB_HAILSTORM_WEATHER = 140,
    GB_FROST_BREATH = 141,
    GB_MYSTIC_WATER = 142,
    GB_NEVER_MELT_ICE = 143,
    GB_FAIRY_FEATHER = 144,
    GB_LUCKY_EGG = 145,
    GB_BLAZE_KICK = 146,     ELDWYRM_RARE = GB_BLAZE_KICK,
    GB_FLAMETHROWER = 147,
    GB_OVERHEAT = 148,
    GB_WILL_O_WISP = 149,
    GB_THUNDER = 150,
    GB_THUNDERBOLT = 151,
    GB_THUNDER_WAVE = 152,
    GB_VOLT_SWITCH = 153,
    GB_ZING_ZAP = 154,
    GB_DRAGON_CLAW = 155,
    GB_SWORDS_DANCE = 156,     DSOTM_RARE = GB_SWORDS_DANCE,
    GB_REST = 157,
    GB_PHANTOM_FORCE = 158,
    GB_SHADOW_BALL = 159,
    GB_DARK_PULSE = 160,
    GB_KNOCK_OFF = 161,
    GB_NASTY_PLOT = 162,
    GB_SUCKER_PUNCH = 163,
    GB_IRON_HEAD = 164,     MONOLITH_RARE = GB_IRON_HEAD,
    GB_METEOR_BEAM = 165,
    GB_ROCK_SLIDE = 166,
    GB_SCORCHING_SANDS = 167,
    GB_10X_IRON,_10X_HP_UP,_10X_ZINC = 168,
    GB_BRICK_BREAK = 169,     WINGED_LION_RARE = GB_BRICK_BREAK,
    GB_DRAIN_PUNCH = 170,
    GB_ACROBATICS = 171,
    GB_AIR_SLASH = 172,
    GB_BODY_PRESS = 173,
    GB_STRENGTH_RARER = 174,     UNIVERSAL_RARE = GB_STRENGTH_RARER,
    GB_BULLET_SEED = 175,     SAPROTROPH_EPIC = GB_BULLET_SEED,
    GB_ENERGY_BALL = 176,
    GB_LUNGE = 177,
    GB_POLLEN_PUFF = 178,
    GB_SLUDGE_BOMB = 179,
    GB_SURF = 180,     NEREID_EPIC = GB_SURF,
    GB_ICE_BEAM = 181,
    GB_PLAY_ROUGH = 182,
    GB_MORE_MONEY = 183,
    GB_DRACO_METEOR = 184,     ELDWYRM_EPIC = GB_DRACO_METEOR,
    GB_CHOICE_SPECS = 185,
    GB_CHOICE_BAND = 186,
    GB_HYPER_BEAM = 187,     DSOTM_EPIC = GB_HYPER_BEAM,
    GB_RETURN = 188,
    GB_PSYCHIC = 189,
    GB_DOUBLE_EDGE = 190,
    GB_IGNORE_RESTRICTIONS = 191,
    GB_THREE_RANDOM_TMS = 192,
    GB_STONE_EDGE = 193,     MONOLITH_EPIC = GB_STONE_EDGE,
    GB_EARTHQUAKE = 194,
    GB_10X_REVIVE = 195,
    GB_FOCUS_BLAST = 196,     WINGED_LION_EPIC = GB_FOCUS_BLAST,
    GB_TAILWIND_WEATHER = 197,
    GB_LENGTH,
};

#endif //GUARD_GAUNTLET_H