gText_Birch_Welcome::
	.string "Whoa! I thought I had a rookie coming,\n"
	.string "but you look pretty experienced!\p"
	.string "$"

gText_Birch_Pokemon:: @ unused. See gText_ThisIsAPokemon in main_menu.c
	.string "Welcome to “POKé47.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I'm BIRCH, and I'm a POKéMON\n"
	.string "researcher here in HOENN.\l"
	.string "Nice to meet you!\p"
	.string "POKéMON from generations 4 to 7,\n"
	.string "like this one, populate this\l"
	.string "special version of HOENN.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Over to you!$"

gText_Birch_BoyOrGirl::
	.string "Would you like to play as a boy,\n"
	.string "or as a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, of course!\p"
	.string "You're the same {PLAYER}{KUN} who's moving\n"
	.string "to my hometown of LITTLEROOT!\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "$"
